project_id = "bewacnnfyhiiwxhhbeem"

[functions.ocr-nota]
verify_jwt = false

[functions.bulk-import]
verify_jwt = false

[functions.import-sales-history]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-insights]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.review-restock]
verify_jwt = false