// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List products in the RRCollections catalog, optionally filtered by category or code/name search.",
  inputSchema: {
    search: z.string().optional().describe("Filter by code (kode) or name (nama), case-insensitive."),
    kategori: z.string().optional().describe("Category filter, e.g. '2 Ons', '3 Ons', '5 Ons', '18g'."),
    only_active: z.boolean().optional().describe("Only return active products (default true)."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, kategori, only_active = true, limit = 50 }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("products").select("id,kode,nama,kategori,is_active").limit(limit);
    if (only_active) q = q.eq("is_active", true);
    if (kategori) q = q.eq("kategori", kategori);
    if (search) q = q.or(`kode.ilike.%${search}%,nama.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-stock.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_stock_default = defineTool2({
  name: "get_stock",
  title: "Get current stock",
  description: "Get current stock quantity and tumpukan for a product by kode (product code) and optional kategori.",
  inputSchema: {
    kode: z2.string().min(1).describe("Product code (kode)."),
    kategori: z2.string().optional().describe("Category, e.g. '2 Ons'. Recommended since kode is unique per kategori.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kode, kategori }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb2(ctx);
    let pq = client.from("products").select("id,kode,nama,kategori").eq("kode", kode);
    if (kategori) pq = pq.eq("kategori", kategori);
    const { data: products, error: pe } = await pq;
    if (pe) return { content: [{ type: "text", text: pe.message }], isError: true };
    if (!products?.length) return { content: [{ type: "text", text: `No product with kode "${kode}"` }], isError: true };
    const ids = products.map((p) => p.id);
    const { data: stocks, error: se } = await client.from("stock").select("product_id,jumlah,tumpukan,tumpukan_detail,updated_at").in("product_id", ids);
    if (se) return { content: [{ type: "text", text: se.message }], isError: true };
    const rows = products.map((p) => {
      const s = stocks?.find((x) => x.product_id === p.id);
      return {
        kode: p.kode,
        nama: p.nama,
        kategori: p.kategori,
        jumlah: s?.jumlah ?? 0,
        tumpukan: s?.tumpukan ?? null,
        tumpukan_detail: s?.tumpukan_detail ?? null,
        updated_at: s?.updated_at ?? null
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { stock: rows }
    };
  }
});

// src/lib/mcp/tools/recent-sales.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var recent_sales_default = defineTool3({
  name: "recent_sales",
  title: "Recent sales",
  description: "List the most recent sales (barang keluar) transactions with product info.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows to return (default 20)."),
    toko: z3.string().optional().describe("Filter by toko (store) name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit = 20, toko }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb3(ctx).from("stock_out").select("id,created_at,toko,qty_pesan,qty_kirim,harga_type,harga_satuan,total_harga,catatan,product_id,products(kode,nama,kategori)").order("created_at", { ascending: false }).order("id", { ascending: false }).limit(limit);
    if (toko) q = q.ilike("toko", `%${toko}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { sales: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/sales-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var sales_summary_default = defineTool4({
  name: "sales_summary",
  title: "Sales summary",
  description: "Summarize sales (barang keluar) over the last N days: total omzet, transactions, and top products.",
  inputSchema: {
    days: z4.number().int().min(1).max(365).optional().describe("Lookback window in days (default 30)."),
    top: z4.number().int().min(1).max(50).optional().describe("Number of top products to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days = 30, top = 10 }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const since = new Date(Date.now() - days * 24 * 60 * 60 * 1e3).toISOString();
    const { data, error } = await sb4(ctx).from("stock_out").select("qty_kirim,total_harga,product_id,products(kode,nama,kategori)").gte("created_at", since).limit(1e4);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const omzet = rows.reduce((s, r) => s + (r.total_harga ?? 0), 0);
    const qty = rows.reduce((s, r) => s + (r.qty_kirim ?? 0), 0);
    const byProduct = /* @__PURE__ */ new Map();
    for (const r of rows) {
      const p = r.products;
      if (!p) continue;
      const key = `${p.kategori}::${p.kode}`;
      const cur = byProduct.get(key) ?? { kode: p.kode, nama: p.nama, kategori: p.kategori, qty: 0, omzet: 0 };
      cur.qty += r.qty_kirim ?? 0;
      cur.omzet += r.total_harga ?? 0;
      byProduct.set(key, cur);
    }
    const top_products = [...byProduct.values()].sort((a, b) => b.qty - a.qty).slice(0, top);
    const summary = {
      window_days: days,
      since,
      transactions: rows.length,
      total_qty: qty,
      total_omzet: omzet,
      top_products
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bewacnnfyhiiwxhhbeem";
var mcp_default = defineMcp({
  name: "rrcollections-mcp",
  title: "RRCollections Stok",
  version: "0.1.0",
  instructions: "Read-only tools over the RRCollections stock manager. Use list_products to browse the catalog, get_stock for current quantities per product code, recent_sales for the latest barang keluar, and sales_summary for omzet and top movers.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_stock_default, recent_sales_default, sales_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
